### ISSUE TITLE
Change default derived stream period to "yesterday"

### ISSUE THREAD

**Issue by mreid-moz** [vitillo/telemetry-batch-view#12]
At the moment the `DerivedStream` runner [defaults to processing "today"](https://github.com/vitillo/telemetry-batch-view/blob/master/src/main/scala/DerivedStream.scala#L159). Can we safely change it to process "yesterday" by default so that we can be sure the day is complete before creating a derived dataset?

This is for the purposes of creating a scheduled job to populate a derived dataset.

**Comment by vitillo** [comment]
Yeah, that makes sense.

**Comment by mreid-moz** [comment]
Closed with #13
